# Generated by Django 4.1 on 2022-08-23 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='yourname', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_userplan', models.CharField(default='100Rs', max_length=6)),
                ('another_userplan', models.CharField(default='200Rs', max_length=6)),
                ('theuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myplans.myuser')),
            ],
        ),
    ]
